### ISSUE TITLE
Misleading click cursor appears for layers without a clickable route

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/ember-mapbox-composer#31]
**Describe the bug**
In staging, when hovering over layers that don't have clickable routes, like MIH and Inclusionary Housing, the cursor changes from the grab hand to the click hand. This is misleading because when you click on them, there isn't any resulting action.

**To Reproduce**
1. Turn on MIH layer
2. Hover over one of the polygons
3. Click
4. See that the polygon is selected in purple, but no pop-up info window opens.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Comment by allthesignals** [comment]
Closed by #ab98ff4ff8ce8cf92297544320d5a61e28ea15f8
